# Generated by Django 5.1.1 on 2024-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deparments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeesId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeesName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfBirth', models.DateTimeField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
